name: Push Master

on: 
  push:
    branches: [ master ]
    tags-ignore:
      - 'v*'

jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - run: npm install
      - run: npm test

  tag:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.CS_ACCESS_TOKEN }}
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Setup git config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - run: npm version prerelease --preid=alpha
