name: CI

on: 
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - run: npm install
      - run: npm test
      - run: vsce package
      - run: npm version prerelease --preid=alpha
